'use strict'
/**
 * sync: bring a widget's locale files up to date with its English default.ts files.
 *
 * Incremental and safe to run any time (on save, before a release, in a watch loop):
 *   - new English keys        -> looked up in the Esri TM, then machine translation if
 *                                configured, otherwise listed for review
 *   - changed English text    -> earlier translations are marked stale and not shipped
 *   - deleted keys            -> removed from every locale file
 *   - hand edits in <loc>.js  -> detected and kept as manual translations
 *   - manual / reviewed text  -> never overwritten
 *
 * State lives in <widget>/i18n/translations.lock.json; review sheets in <widget>/i18n/review.
 */
const fs = require('fs')
const path = require('path')
const { loadDefaultTs, loadLocaleJs, formatLocaleJs, readJson, writeJson, readText } = require('./loaders')
const { EXB_LOCALES } = require('./locales')
const { norm, looseNorm, adapt } = require('./match')
const { machineTranslate } = require('./mt')
const { toCsv } = require('./csv')

const PARTS = ['runtime', 'setting', 'guide']
const SHIPPED = new Set(['manual', 'existing', 'esri', 'esri-check', 'community'])
const LOCK_VERSION = 2
const HEADER = 'Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync.'
const REVIEW_HEADERS = ['part', 'key', 'status', 'english', 'suggestion', 'translation', 'approve', 'notes']

const crypto = require('crypto')
function hash (s) { return crypto.createHash('sha1').update(String(s)).digest('hex').slice(0, 12) }
function englishHash (en, keys) { return hash(keys.map(k => k + '\u0000' + en[k]).join('\u0001')) }

function isWidgetFolder (dir) {
  const m = readJson(path.join(dir, 'manifest.json'), null)
  return !!(m && (m.type === 'widget' || !m.type) && fs.existsSync(path.join(dir, 'src')))
}

function discoverParts (widgetDir) {
  return PARTS.map(p => ({ part: p, dir: path.join(widgetDir, 'src', p, 'translations') }))
    .filter(p => fs.existsSync(path.join(p.dir, 'default.ts')))
}

/** Every English string a widget needs, as TM lookup keys. */
function neededKeys (widgetDir) {
  const set = new Set()
  for (const p of discoverParts(widgetDir)) {
    const en = loadDefaultTs(path.join(p.dir, 'default.ts'))
    for (const k of Object.keys(en)) if (typeof en[k] === 'string') { set.add(norm(en[k])); set.add('L:' + looseNorm(en[k])) }
  }
  return set
}

function lockPath (widgetDir) { return path.join(widgetDir, 'i18n', 'translations.lock.json') }

function readLock (widgetDir) {
  const lock = readJson(lockPath(widgetDir), null)
  if (lock && lock.version === LOCK_VERSION && lock.parts) return lock
  return { version: LOCK_VERSION, parts: {} }
}

function shipped (entry, cfg) {
  if (!entry || typeof entry.t !== 'string') return false
  return SHIPPED.has(entry.src) || (entry.src === 'machine' && cfg.shipMachine)
}

/** Pick an Esri translation. Returns { t, alt[] } or null. */
function fromEsri (tm, english, locale) {
  if (!tm) return null
  let cands = tm.lookup(english, locale)
  let close = false
  if (!cands.length && tm.lookupLoose) { cands = tm.lookupLoose(english, locale); close = cands.length > 0 }
  const adapted = []
  for (const c of cands) {
    const t = adapt(english, c.text, c.en, locale)
    if (!t) continue
    // Some Esri bundles ship English in a locale file (untranslated upstream). Such a match is no
    // translation: skip it so a real candidate, the shared memory or CLDR can fill the key.
    if (!/^en\b/i.test(locale) && t.trim() === String(english).trim() && /[a-z]{3}/i.test(english)) continue
    const same = adapted.find(a => a.t === t)
    if (same) { same.count += c.count; same.prio = Math.max(same.prio, c.prio) } else adapted.push({ t, count: c.count, prio: c.prio, sources: c.sources })
  }
  if (!adapted.length) return null
  adapted.sort((a, b) => (b.prio - a.prio) || (b.count - a.count))
  const top = adapted[0]
  // Ambiguous when another candidate from an equally trusted source is used about as often.
  const rivals = adapted.slice(1).filter(a => a.prio === top.prio && a.count * 2 >= top.count)
  return { t: top.t, alt: rivals.slice(0, 3).map(a => a.t), sources: top.sources, close, closeEn: close ? cands[0].en : undefined }
}

function writeIfChanged (file, content) {
  let old = null
  try { old = readText(file) } catch (e) { if (e.code !== 'ENOENT') throw e }
  if (old === content) return false
  fs.mkdirSync(path.dirname(file), { recursive: true })
  const temp = path.join(path.dirname(file), '.' + path.basename(file) + '.' + process.pid + '.' + require('crypto').randomBytes(8).toString('hex') + '.tmp')
  try {
    fs.writeFileSync(temp, content, { encoding: 'utf8', flag: 'wx' })
    fs.renameSync(temp, file)
  } finally {
    try { fs.unlinkSync(temp) } catch (e) { if (e.code !== 'ENOENT') throw e }
  }
  return true
}

async function syncWidget (widgetDir, ctx) {
  const { cfg, tm, provider, memory, locales, log = () => {}, dryRun = false } = ctx
  const parts = discoverParts(widgetDir)
  const name = path.basename(widgetDir)
  const report = { widget: name, dir: widgetDir, parts: {}, written: [], locales, totals: {} }
  if (!parts.length) { report.skipped = 'no src/<part>/translations/default.ts'; return report }

  const prevLock = readLock(widgetDir)
  const hadLock = fs.existsSync(lockPath(widgetDir))
  const lock = { version: LOCK_VERSION, generator: 'exb-i18n-kit', parts: {} }
  const review = {} // locale -> rows

  for (const { part, dir } of parts) {
    const en = loadDefaultTs(path.join(dir, 'default.ts'))
    const keys = Object.keys(en).filter(k => typeof en[k] === 'string')
    const prevPart = prevLock.parts[part] || { locales: {} }
    lock.parts[part] = { en: englishHash(en, keys), keys: keys.length, hashes: {}, locales: {} }
    for (const k of keys) lock.parts[part].hashes[k] = hash(en[k])
    const prevHashes = prevPart.hashes || {}
    report.parts[part] = { keys: keys.length, locales: {} }

    for (const loc of locales) {
      const file = path.join(dir, `${loc}.js`)
      const fileText = fs.existsSync(file) ? readText(file) : null
      let existing = null
      if (fileText != null) { try { existing = loadLocaleJs(file) } catch (e) { log(`  ! ${path.relative(widgetDir, file)}: ${e.message}`) } }
      const prevLoc = (prevPart.locales && prevPart.locales[loc]) || {}
      const prev = prevLoc.entries || {}
      // Only look for hand edits when the file differs from what the last sync wrote.
      const fileEdited = existing && (!hadLock || !prevLoc.file || prevLoc.file !== hash(fileText))
      const next = {}
      const pendingMt = []

      for (const key of keys) {
        const E = en[key]
        const h = hash(E)
        const p = prev[key]
        const same = p && p.h === h
        const fileVal = existing && typeof existing[key] === 'string' ? existing[key] : null
        let esri // computed once, lazily
        const getEsri = () => (esri === undefined ? (esri = fromEsri(tm, E, loc)) : esri)

        // 1. Hand edit in the locale file (or a file that existed before this tool).
        if (fileEdited && fileVal != null && fileVal !== E && !(p && p.fresh)) {
          const lastWritten = same && (p.src === 'manual' || p.src === 'existing' || (p.src === 'machine' && cfg.shipMachine)) ? p.t : (getEsri() ? getEsri().t : null)
          if (fileVal !== lastWritten) { next[key] = { t: fileVal, src: hadLock ? 'manual' : 'existing', h }; continue }
        }
        // 2. Human-owned translations survive while the English is unchanged.
        if (same && (p.src === 'manual' || p.src === 'existing')) { next[key] = { t: p.t, src: p.src, h }; continue }
        // 3. Esri translation memory, re-evaluated every run so new Esri releases improve it.
        if (getEsri()) {
          next[key] = esri.alt.length || esri.close
            ? Object.assign({ t: esri.t, src: 'esri-check', h, alt: esri.alt }, esri.close ? { near: esri.closeEn } : {})
            : { t: esri.t, src: 'esri', h }
          continue
        }
        // 3b. No Esri install here (for example a GitHub Action): keep what the last sync shipped
        //     for this key while its English is unchanged, so Esri wording is not lost in CI.
        if (!tm && fileVal != null && fileVal !== E && prevHashes[key] === h && !(same && p.src === 'machine')) {
          next[key] = { t: fileVal, src: 'esri', h, kept: true }
          continue
        }
        // 4. Shared community memory (GitHub): reviewed entries ship as community, the rest as machine.
        const mem = memory && memory.lookup(E, loc)
        if (mem) { next[key] = { t: mem.t, src: mem.reviewed ? 'community' : 'machine', h }; continue }
        // 5. A machine translation stays until Esri has one or a person replaces it.
        if (same && p.src === 'machine') { next[key] = { t: p.t, src: 'machine', h }; continue }
        // 5. Stale: the English changed under a translation a person or a machine produced.
        if (p && !same && (p.src === 'manual' || p.src === 'existing' || p.src === 'machine' || p.src === 'stale')) {
          next[key] = { src: 'stale', h, old: p.t || p.old }
        } else next[key] = { src: 'missing', h }
        pendingMt.push(key)
      }

      // 6. Machine translation for whatever is left.
      if (provider && pendingMt.length && !dryRun) {
        try {
          const out = await machineTranslate(provider, pendingMt.map(k => en[k]), loc)
          pendingMt.forEach((k, i) => { if (out[i]) next[k] = { t: out[i], src: 'machine', h: next[k].h } })
        } catch (e) {
          log(`  ! machine translation (${loc}): ${e.message}`)
        }
      }

      // Output in default.ts key order.
      const out = {}
      const counts = { esri: 0, 'esri-check': 0, community: 0, manual: 0, existing: 0, machine: 0, stale: 0, missing: 0 }
      const kept = {}
      for (const key of keys) {
        const n = next[key]
        counts[n.src] = (counts[n.src] || 0) + 1
        if (shipped(n, cfg)) out[key] = n.t
        else if (cfg.fillMissingWithEnglish) out[key] = en[key]
        // The lock keeps only what cannot be recomputed: human, machine and stale entries.
        if (n.src === 'manual' || n.src === 'existing' || n.src === 'machine') kept[key] = { t: n.t, src: n.src, h: n.h }
        else if (n.src === 'stale') kept[key] = { src: 'stale', h: n.h, old: n.old }
        const needsReview = n.src === 'missing' || n.src === 'stale' || n.src === 'machine' || n.src === 'esri-check'
        if (needsReview) {
          (review[loc] = review[loc] || []).push({
            part,
            key,
            status: n.src,
            english: en[key],
            suggestion: n.src === 'esri-check' ? [n.t, ...(n.alt || [])].join(' | ') : (n.t || n.old || ''),
            translation: '',
            approve: '',
            notes: n.src === 'stale' ? 'English changed since this was translated' : n.src === 'machine' ? 'Machine translation, check wording' : n.src === 'esri-check' ? (n.near ? `Close match: Esri translates "${n.near}"` : 'Esri uses more than one wording; approve keeps the first') : ''
          })
        }
      }
      const content = formatLocaleJs(out, HEADER)
      lock.parts[part].locales[loc] = { file: hash(content), counts, entries: kept }
      report.parts[part].locales[loc] = counts
      for (const st of Object.keys(counts)) report.totals[st] = (report.totals[st] || 0) + counts[st]

      if (!dryRun && writeIfChanged(file, content)) report.written.push(path.relative(widgetDir, file))
    }
  }
  report.review = review

  if (!dryRun) {
    // Keep the lock stable across no-op runs so it does not churn in git.
    if (JSON.stringify(prevLock.parts) !== JSON.stringify(lock.parts) || !hadLock) {
      fs.mkdirSync(path.dirname(lockPath(widgetDir)), { recursive: true })
      writeJson(lockPath(widgetDir), lock)
    }
    const reviewDir = path.join(widgetDir, 'i18n', 'review')
    if (ctx.writeReview) {
      fs.mkdirSync(reviewDir, { recursive: true })
      for (const loc of locales) {
        const f = path.join(reviewDir, `${loc}.csv`)
        if (review[loc] && review[loc].length) writeIfChanged(f, toCsv(REVIEW_HEADERS, review[loc]))
        else if (fs.existsSync(f)) fs.unlinkSync(f)
      }
    }
    writeIfChanged(path.join(widgetDir, 'i18n', 'STATUS.md'), statusMarkdown(report))
    if (updateManifest(widgetDir, locales)) report.written.push('manifest.json')
  }
  return report
}

/** translatedLocales must start with "en" (EB reads default.ts for index 0). */
function updateManifest (widgetDir, locales) {
  const file = path.join(widgetDir, 'manifest.json')
  const text = readText(file)
  const m = JSON.parse(text)
  const have = new Set((m.translatedLocales || []).map(String))
  for (const l of locales) have.add(l)
  have.delete('en')
  const ordered = ['en', ...EXB_LOCALES.filter(l => have.has(l)), ...[...have].filter(l => !EXB_LOCALES.includes(l))]
  if (JSON.stringify(ordered) === JSON.stringify(m.translatedLocales)) return false
  m.translatedLocales = ordered
  const indent = (text.match(/\n([ \t]+)"/) || [null, '  '])[1]
  const eol = text.includes('\r\n') ? '\r\n' : '\n'
  fs.writeFileSync(file, JSON.stringify(m, null, indent).replace(/\n/g, eol) + eol, 'utf8')
  return true
}

function pct (n, d) { return d ? Math.round((n / d) * 100) : 0 }

function statusMarkdown (report) {
  const lines = [`# Translation status: ${report.widget}`, '', 'Coverage counts known catalog entries, not UI wiring or linguistic quality. Run `audit` and test the target locale. Generated by exb-i18n-kit `sync`. Do not edit. To translate what is missing: `exb-i18n review <widget> --locales es` writes `i18n/review/es.csv`; fill the translation column (or put x in approve) and run `exb-i18n import <widget> i18n/review/es.csv`.', '']
  lines.push('| Locale | Strings | Esri | Esri (check) | Community | Manual | Machine | Stale | Missing | Translated |')
  lines.push('|---|---|---|---|---|---|---|---|---|---|')
  for (const loc of report.locales) {
    const c = { esri: 0, 'esri-check': 0, community: 0, manual: 0, existing: 0, machine: 0, stale: 0, missing: 0 }
    let total = 0
    for (const part of Object.keys(report.parts)) {
      const pc = report.parts[part].locales[loc] || {}
      for (const s of Object.keys(pc)) { c[s] = (c[s] || 0) + pc[s]; total += pc[s] }
    }
    const done = c.esri + c['esri-check'] + c.community + c.manual + c.existing + c.machine
    lines.push(`| ${loc} | ${total} | ${c.esri} | ${c['esri-check']} | ${c.community} | ${c.manual + c.existing} | ${c.machine} | ${c.stale} | ${c.missing} | ${pct(done, total)}% |`)
  }
  lines.push('', 'Esri: matched in translations Esri ships with Experience Builder and the ArcGIS Maps SDK. Esri (check): Esri uses more than one wording. Community: reviewed entries from the shared GitHub translation memory. Machine: not reviewed yet. Untranslated strings show in English.', '')
  return lines.join('\n')
}

module.exports = { hash, englishHash, syncWidget, discoverParts, neededKeys, isWidgetFolder, readLock, lockPath, updateManifest, REVIEW_HEADERS, shipped }
