'use strict'
/**
 * wire: the second pass after extract, for any custom widget. It fixes what extract leaves behind
 * ("no translator in scope") and the patterns extract does not look at:
 *
 *   1. Hard-coded English anywhere under src/:
 *        JSX text and UI attributes            <b>Clear</b>  title="Undo"
 *        props passed without JSX              jsx('div', { children: 'Mailing Labels' })
 *        UI fields of object literals          { label: 'Point', placeholder: 'Search…' }
 *        config fallbacks                      config.areaButtonText || 'Freehand Area'
 *        label / hint / text helpers           getToolHint () { return 'Click to add a point' }
 *        status setters and UI calls           setStatus('Searching…')  confirm('Reset?')
 *      become __t('key') calls. __t lives in a small helper per part (src/<part>/i18n-t.ts) that
 *      every module of that part imports, so strings outside the component tree translate too.
 *   2. Direct reads of the messages object    defaultMessages.searching      -> __m.searching
 *      (__m returns the app-language string when the widget's intl has it.)
 *   3. Translators that never ask intl        const t = (id) => defaultMessages[id] ...
 *      get "use intl first" in front of their body.
 *   4. The entry component of each part (runtime/widget.tsx, setting/setting.tsx) and every
 *      default-exported component in a changed file hand their intl to the helper (__setIntl).
 *
 * Left alone on purpose: strings the same file also compares against (=== 'Freehand',
 * label.includes('Freehand'), case 'Freehand Area':), strings passed to constructors
 * (new GraphicsLayer({ title })), console / Error messages, keys and ids.
 */
const fs = require('fs')
const path = require('path')
const { loadDefaultTs } = require('./loaders')
const { looksLikeUiText, loadTypeScript } = require('./audit')
const { makeKeyer, appendKeys, decodeEntities, jsxTextValue } = require('./extract')

const { uiExpressions, sinkIndexes, fixedLocaleArgument } = require('./ui-flow')

const HELPER = 'i18n-t'
const UI_ATTRS = new Set(['title', 'aria-label', 'aria-description', 'aria-valuetext', 'aria-roledescription', 'aria-placeholder',
  'placeholder', 'label', 'alt', 'tooltip', 'helperText', 'emptyText', 'confirmText', 'cancelText', 'okText', 'text', 'description', 'heading'])
const UI_PROPS = new Set([...UI_ATTRS, 'children', 'ariaLabel', 'hint', 'caption', 'buttonText', 'tooltipText', 'subtitle', 'emptyMessage', 'loadingText'])
const STATE_PROPS = /^(status|statusMsg|statusMessage|statusText|message|msg|error|errorMsg|errorMessage|notice|hint|warning|info|note|toast|banner|loadingMessage|emptyMessage|progressText)$/
const SINKS = new Set(['announceStatus', 'announce', 'alert', 'confirm', 'setStatus', 'showMessage', 'notify', 'toast', 'setStatusMessage', 'setErrorMessage', 'setStatusMsg', 'setMessage', 'setError', 'setNotice', 'setHint', 'setWarning', 'setInfo', 'setLoadingMessage', 'setBanner', 'setToast'])
const HELPER_FN = /(label|labels|text|title|hint|message|caption|tooltip|status|description|instruction|instructions|prompt|placeholder|heading|summary|tip)$/i
const FALLBACK_LEFT = /(config|props|label|text|title|caption|placeholder|hint|message|tooltip)/i
const TRANSLATE_FNS = new Set(['nls', 't', 'translate', 'formatMessage', 'translateMessage', 'getI18nMessage', 'i18n', '__t', '__tc', 'helpT'])
const COMPARE_FNS = new Set(['includes', 'startsWith', 'endsWith', 'indexOf', 'lastIndexOf', 'match', 'test', 'search', 'localeCompare', 'replace', 'split'])
const KEY_NAMES = /^(Esc|Ctrl|Shift|Alt|Enter|Tab|Del|Delete|Home|End|PgUp|PgDn|Space|Backspace|Cmd|Option|Meta)$/
const looksLikeCode = s => /^[@#][\w-]+|^\.[\w-]+(?:\s*[{:.]|$)/.test(s.trim()) || (/[{};]/.test(s) && /:/.test(s)) || /^\s*</.test(s)
const isUi = s => looksLikeUiText(s) && !looksLikeCode(s)
const MESSAGES_IMPORT = /(^|\/)translations\/default$/

const localeHelper = `/** Current app locale for number/date formatting; browser locale before intl is available. */
export function __locale (): string | undefined {
  const locale = intl && intl.locale
  if (typeof locale !== 'string' || !locale) return undefined
  try { return Intl.getCanonicalLocales(locale)[0] } catch (e) { return undefined }
}
`

function helperSource (rel) {
  return `/* Generated by exb-i18n-kit (wire). Shares the widget's intl with every module of this part,
   so strings outside the component tree follow the app language too. Safe to keep in git. */
import __messages from '${rel}'

let intl: any = null

/** Called by the entry component on every render. */
export function __setIntl (i: any): void { if (i && typeof i.formatMessage === 'function') intl = i }

${localeHelper}

/** App-language text for a key in translations/default.ts; English (with {values} filled) when there is none. */
export function __t (id: string, values?: { [key: string]: any }): string {
  const msg: string = (__messages as any)[id] ?? id
  if (intl) { try { return intl.formatMessage({ id, defaultMessage: msg }, values) } catch (e) { } }
  return String(msg).replace(/\\{(\\w+)\\}/g, (m: string, k: string) => (values && values[k] != null ? String(values[k]) : m))
}

/** config.x || 'Default' made translatable: the app-language default when the value is empty or still the English default. */
export function __tc (value: any, id: string, values?: { [key: string]: any }): string {
  if (value == null || value === '' || value === (__messages as any)[id]) return __t(id, values)
  return value
}

/** Used in front of hand-written translators: the app-language text, or undefined to keep their own logic. */
export function __tryIntl (id: any, values?: any): string | undefined {
  if (!intl || typeof id !== 'string' || !intl.messages || typeof intl.messages[id] !== 'string') return undefined
  try { return intl.formatMessage({ id, defaultMessage: (__messages as any)[id] ?? id }, values) } catch (e) { return undefined }
}

/** The messages object, but every string comes from the app language when the widget intl has it. */
export const __m: any = new Proxy(__messages as any, {
  get: (target: any, key: any) => {
    const v = target[key]
    if (typeof key !== 'string' || typeof v !== 'string') return v
    const m = intl && intl.messages ? intl.messages[key] : undefined
    return typeof m === 'string' ? m : v
  }
})
`
}

function walk (dir, out = []) {
  if (!fs.existsSync(dir)) return out
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name === 'node_modules' || e.name === 'vendor' || e.name === 'translations' || e.name.startsWith('.')) continue
    const p = path.join(dir, e.name)
    if (e.isDirectory()) walk(p, out)
    else if (/\.(tsx|ts|jsx|js)$/.test(e.name) && !/\.d\.ts$/.test(e.name) && !/\.test\./.test(e.name) && e.name !== HELPER + '.ts') out.push(p)
  }
  return out
}

function relImport (fromFile, toFileNoExt) {
  let r = path.relative(path.dirname(fromFile), toFileNoExt).replace(/\\/g, '/')
  if (!r.startsWith('.')) r = './' + r
  return r
}

function wireFile (ts, file, ctx) {
  const text = fs.readFileSync(file, 'utf8')
  const eol = text.includes('\r\n') ? '\r\n' : '\n'
  const src = text.replace(/\r\n/g, '\n')
  const sf = ts.createSourceFile(file, src, ts.ScriptTarget.Latest, true, /x$/.test(file) ? ts.ScriptKind.TSX : ts.ScriptKind.TS)
  const lineOf = n => sf.getLineAndCharacterOfPosition(n.getStart(sf)).line + 1
  const edits = []
  const report = []
  const use = new Set()
  const localT = /\b(const|let|function)\s+__t\b/.test(src) // a hand-wired module translator already here
  const tCall = (key, vals) => { use.add('__t'); return `__t(${JSON.stringify(key)}${vals && vals.length ? `, { ${vals.join(', ')} }` : ''})` }

  // ---- strings this file compares against: never translate those (or text that contains them)
  const guarded = new Set()
  const lit = n => (ts.isStringLiteral(n) || ts.isNoSubstitutionTemplateLiteral(n)) ? n.text : null
  const scanGuards = n => {
    if (ts.isBinaryExpression(n) && [ts.SyntaxKind.EqualsEqualsEqualsToken, ts.SyntaxKind.ExclamationEqualsEqualsToken, ts.SyntaxKind.EqualsEqualsToken, ts.SyntaxKind.ExclamationEqualsToken].includes(n.operatorToken.kind)) {
      for (const s of [lit(n.left), lit(n.right)]) if (s) guarded.add(s)
    }
    if (ts.isCaseClause(n) && lit(n.expression)) guarded.add(lit(n.expression))
    if (ts.isCallExpression(n) && ts.isPropertyAccessExpression(n.expression) && COMPARE_FNS.has(n.expression.name.text)) for (const a of n.arguments) if (lit(a)) guarded.add(lit(a))
    ts.forEachChild(n, scanGuards)
  }
  scanGuards(sf)
  const isGuarded = s => guarded.has(s) || guarded.has(String(s).trim())

  // ---- where a node sits
  const inside = (n, pred) => { for (let p = n.parent; p; p = p.parent) if (pred(p)) return p; return null }
  const calleeName = e => ts.isIdentifier(e) ? e.text : ts.isPropertyAccessExpression(e) ? e.name.text : ''
  const skipContext = n => inside(n, p =>
    (ts.isCallExpression(p) && (TRANSLATE_FNS.has(calleeName(p.expression)) || /^console\./.test(p.expression.getText(sf)) || calleeName(p.expression) === 'require')) ||
    ts.isNewExpression(p) || ts.isImportDeclaration(p) || ts.isExportDeclaration(p) || ts.isTypeNode(p) || ts.isEnumDeclaration(p) ||
    (ts.isElementAccessExpression(p) && within(n, p.argumentExpression)) || (ts.isCaseClause(p) && within(n, p.expression)) || ts.isTaggedTemplateExpression(p) ||
    (ts.isJsxElement(p) && /^(style|script|code|pre|kbd)$/.test(p.openingElement.tagName.getText(sf))) ||
    (ts.isPropertyAssignment(p) && /^(key|id|className|class|type|name|role|value|href|src|icon|tool|mode|css|style|testId|dataKey)$/.test(propName(p))))
  function within (n, outer) { return outer && n.pos >= outer.pos && n.end <= outer.end }
  function propName (p) { const n = p.name; return n && (ts.isIdentifier(n) || ts.isStringLiteral(n)) ? n.text : '' }

  const done = new Set()
  const english = s => decodeEntities(s)
  function valueSource (value) {
    const replacements = []
    const scan = n => {
      const arg = ctx.localizeFormats && fixedLocaleArgument(ts, n)
      if (arg) {
        use.add('__locale')
        const at = arg === n ? n.arguments.pos : arg.getStart(sf)
        replacements.push({ start: at, end: arg === n ? at : arg.end })
      }
      ts.forEachChild(n, scan)
    }
    scan(value)
    let out = value.getText(sf)
    const start = value.getStart(sf)
    for (const r of replacements.sort((a, b) => b.start - a.start)) out = out.slice(0, r.start - start) + '__locale()' + out.slice(r.end - start)
    return out
  }
  function expressionEdit (e, replacement) {
    if (!inside(e, p => ts.isFunctionLike(p))) {
      const p = e.parent
      if (p && ts.isPropertyAssignment(p) && p.initializer === e) {
        // Module metadata is evaluated before the first widget render. A
        // getter reads the current app locale when the UI consumes the value.
        edits.push({ start: p.getStart(sf), end: p.end, text: `get ${p.name.getText(sf)} () { return ${replacement} }` })
        return
      }
      report.push({ line: lineOf(e), why: 'by hand: module or class initializer needs translation at render time', text: e.getText(sf).slice(0, 160) })
      return
    }
    edits.push({ start: e.getStart(sf), end: e.end, text: replacement })
  }
  function fallbackEdit (n) {
    const r = n.right
    const key = n.pos + ':' + n.end
    if (done.has(key) || done.has(r.pos + ':' + r.end)) return true
    const core = (ts.isStringLiteral(r) || ts.isNoSubstitutionTemplateLiteral(r)) ? english(r.text.trim()) : ''
    if (!core || core !== r.text || !isUi(core) || isGuarded(core) || skipContext(r) || !FALLBACK_LEFT.test(n.left.getText(sf))) return false
    if (/[[\]()]/.test(n.left.getText(sf)) || /\b(nls|t|translate|formatMessage|__t)\s*\(/.test(n.left.getText(sf))) return false
    // config.x || 'Default'  ->  __tc(config.x, 'key'): also translates a config value that is
    // still the English default (a settings panel that saved the default as typed text).
    use.add('__tc'); done.add(key); done.add(r.pos + ':' + r.end)
    expressionEdit(n, `__tc(${n.left.getText(sf)}, ${JSON.stringify(ctx.keyFor(core))})`)
    report.push({ line: lineOf(n), why: 'fallback', text: core })
    return true
  }
  function replaceExpr (e, why) {
    if (!e || done.has(e.pos + ':' + e.end)) return
    if (ts.isParenthesizedExpression(e)) return replaceExpr(e.expression, why)
    if (ts.isBinaryExpression(e) && e.operatorToken.kind === ts.SyntaxKind.PlusToken) {
      if (skipContext(e)) return
      const pieces = []
      const flatten = n => {
        if (ts.isBinaryExpression(n) && n.operatorToken.kind === ts.SyntaxKind.PlusToken && (ts.isStringLiteral(n.left) || ts.isNoSubstitutionTemplateLiteral(n.left) || ts.isBinaryExpression(n.left))) { flatten(n.left); pieces.push(n.right) }
        else pieces.push(n)
      }
      flatten(e)
      // Only flatten a chain that starts with text: a + b + 'items' can
      // perform arithmetic before it becomes a string.
      if (!pieces.length || !(ts.isStringLiteral(pieces[0]) || ts.isNoSubstitutionTemplateLiteral(pieces[0]))) return
      let msg = ''; const vals = []; let i = 0
      for (const p of pieces) {
        if (ts.isStringLiteral(p) || ts.isNoSubstitutionTemplateLiteral(p)) msg += p.text
        else { const name = `value${++i}`; msg += `{${name}}`; vals.push(`${name}: ${valueSource(p)}`) }
      }
      if (!isUi(msg.replace(/\{\w+\}/g, ' ')) || isGuarded(msg) || /[{}]/.test(msg.replace(/\{\w+\}/g, ' '))) return
      done.add(e.pos + ':' + e.end)
      expressionEdit(e, tCall(ctx.keyFor(english(msg)), vals))
      report.push({ line: lineOf(e), why, text: msg })
      return
    }
    if (ts.isConditionalExpression(e)) { replaceExpr(e.whenTrue, why); replaceExpr(e.whenFalse, why); return }
    if (ts.isBinaryExpression(e) && [ts.SyntaxKind.BarBarToken, ts.SyntaxKind.QuestionQuestionToken].includes(e.operatorToken.kind)) { if (!fallbackEdit(e)) replaceExpr(e.right, why); return }
    if (ts.isArrayLiteralExpression(e)) { e.elements.forEach(x => replaceExpr(x, why)); return }
    if (ts.isStringLiteral(e) || ts.isNoSubstitutionTemplateLiteral(e)) {
      const raw = e.text
      const core = english(raw.trim())
      if (!core || !isUi(core) || isGuarded(raw) || isGuarded(core) || skipContext(e)) return
      const lead = raw.match(/^\s*/)[0]; const trail = raw.match(/\s*$/)[0]
      const call = tCall(ctx.keyFor(core))
      done.add(e.pos + ':' + e.end)
      expressionEdit(e, lead || trail ? `${JSON.stringify(lead)} + ${call} + ${JSON.stringify(trail)}` : call)
      report.push({ line: lineOf(e), why, text: core })
      return
    }
    if (ts.isTemplateExpression(e)) {
      if (skipContext(e)) return
      const names = new Set(); const vals = []
      let msg = e.head.text
      for (const sp of e.templateSpans) {
        const x = sp.expression
        let n = ts.isIdentifier(x) ? x.text : ts.isPropertyAccessExpression(x) ? x.name.text : (ts.isCallExpression(x) && ts.isPropertyAccessExpression(x.expression) ? x.expression.name.text : 'value')
        n = n.replace(/\W/g, '') || 'value'; let u = n; let i = 2
        while (names.has(u)) u = n + i++
        names.add(u); vals.push(`${u}: ${valueSource(x)}`)
        msg += '{' + u + '}' + sp.literal.text
      }
      const plain = msg.replace(/\{\w+\}/g, ' ')
      if (/[{}]/.test(plain) || !isUi(plain) || isGuarded(msg)) return
      done.add(e.pos + ':' + e.end)
      const lead = msg.match(/^\s*/)[0]; const trail = msg.match(/\s*$/)[0]
      const call = tCall(ctx.keyFor(english(msg.trim())), vals)
      expressionEdit(e, lead || trail ? `${JSON.stringify(lead)} + ${call} + ${JSON.stringify(trail)}` : call)
      report.push({ line: lineOf(e), why, text: msg })
    }
  }

  // ---- direct reads of an imported messages object
  const msgNames = new Set()
  for (const st of sf.statements) {
    if (ts.isImportDeclaration(st) && st.importClause && st.importClause.name && MESSAGES_IMPORT.test(st.moduleSpecifier.text)) msgNames.add(st.importClause.name.text)
  }
  const isMsgObj = e => {
    while (ts.isParenthesizedExpression(e) || ts.isAsExpression(e) || (ts.TypeAssertionExpression && ts.isTypeAssertionExpression && ts.isTypeAssertionExpression(e))) e = e.expression
    return ts.isIdentifier(e) && msgNames.has(e.text)
  }

  // ---- translators that never ask intl:  (id, values?) => { ... messages[id] ... }  with no intl
  function patchTranslator (fn) {
    if (!fn.body || !ts.isBlock(fn.body) || !fn.parameters.length || !ts.isIdentifier(fn.parameters[0].name)) return
    const body = fn.body.getText(sf)
    if (/intl|formatMessage|__tryIntl|useTranslation|useIntl/.test(body)) return
    let reads = false
    const look = n => { if (ts.isElementAccessExpression(n) && isMsgObj(n.expression) && ts.isIdentifier(n.argumentExpression) && n.argumentExpression.text === fn.parameters[0].name.text) reads = true; if (!reads) ts.forEachChild(n, look) }
    look(fn.body)
    if (!reads) return
    const p0 = fn.parameters[0].name.text
    const p1 = fn.parameters[1] && ts.isIdentifier(fn.parameters[1].name) ? fn.parameters[1].name.text : 'undefined'
    use.add('__tryIntl')
    edits.push({ start: fn.body.getStart(sf) + 1, end: fn.body.getStart(sf) + 1, text: `\n    { const __i = __tryIntl(${p0}, ${p1}); if (__i !== undefined) return __i }` })
    report.push({ line: lineOf(fn), why: 'translator now asks intl first', text: '' })
  }

  const visit = n => {
    if (ctx.localizeFormats && ts.isCallExpression(n)) {
      const arg = fixedLocaleArgument(ts, n)
      if (arg) {
        use.add('__locale')
        const start = n.getStart(sf)
        const at = arg === n ? n.arguments.pos : arg.getStart(sf)
        const end = arg === n ? at : arg.end
        const original = n.getText(sf)
        expressionEdit(n, original.slice(0, at - start) + '__locale()' + original.slice(end - start))
        report.push({ line: lineOf(n), why: 'number/date format now follows the app locale', text: arg === n ? 'browser locale' : arg.getText(sf) })
      }
    }
    // 1. JSX
    if (ts.isJsxText(n)) {
      const raw = n.getText(sf)
      const value = english(jsxTextValue(raw)).trim()
      if (value && isUi(value) && !/^[{}&]/.test(value) && !isGuarded(value) && !skipContext(n)) {
        const s = n.getStart(sf) + raw.search(/\S/)
        const e = n.getStart(sf) + raw.replace(/\s+$/, '').length
        edits.push({ start: s, end: e, text: `{${tCall(ctx.keyFor(value))}}` })
        report.push({ line: lineOf(n), why: 'JSX text', text: value })
      }
    } else if (ts.isJsxExpression(n) && n.expression && n.parent && (ts.isJsxElement(n.parent) || ts.isJsxFragment(n.parent))) {
      replaceExpr(n.expression, 'JSX child')
    } else if (ts.isJsxAttribute(n) && UI_ATTRS.has(n.name.getText(sf)) && n.initializer) {
      const init = n.initializer
      if (ts.isStringLiteral(init)) {
        const v = english(init.text.trim())
        if (v && isUi(v) && !isGuarded(init.text)) {
          edits.push({ start: init.getStart(sf), end: init.end, text: `{${tCall(ctx.keyFor(v))}}` })
          report.push({ line: lineOf(init), why: `${n.name.getText(sf)}=`, text: v })
        }
      } else if (ts.isJsxExpression(init) && init.expression) replaceExpr(init.expression, `${n.name.getText(sf)}=`)
    }
    // 1b. object literals, fallbacks, helper returns, sinks, setState
    if (ts.isPropertyAssignment(n)) {
      const name = propName(n)
      const obj = n.parent
      const setState = obj && obj.parent && ts.isCallExpression(obj.parent) && /^(setState)$/.test(calleeName(obj.parent.expression))
      if (UI_PROPS.has(name) && ts.isCallExpression(n.initializer) && /^__t[c]?$/.test(calleeName(n.initializer.expression)) && !inside(n, p => ts.isFunctionLike(p))) {
        expressionEdit(n.initializer, n.initializer.getText(sf))
        report.push({ line: lineOf(n), why: 'module UI metadata now translates when read', text: name })
      }
      if (UI_PROPS.has(name) || (setState && STATE_PROPS.test(name))) replaceExpr(n.initializer, `${name}:`)
    }
    if (ts.isBinaryExpression(n) && [ts.SyntaxKind.BarBarToken, ts.SyntaxKind.QuestionQuestionToken].includes(n.operatorToken.kind) && FALLBACK_LEFT.test(n.left.getText(sf)) && !/\b(nls|t|translate|formatMessage|__t)\s*\(/.test(n.left.getText(sf))) {
      if (!fallbackEdit(n)) replaceExpr(n.right, 'fallback')
    }
    if (ts.isReturnStatement(n) && n.expression) {
      const fn = inside(n, p => ts.isFunctionLike(p))
      let fname = ''
      if (fn) {
        if (fn.name && ts.isIdentifier(fn.name)) fname = fn.name.text
        else if (fn.parent && ts.isVariableDeclaration(fn.parent) && ts.isIdentifier(fn.parent.name)) fname = fn.parent.name.text
        else if (fn.parent && ts.isPropertyDeclaration(fn.parent) && ts.isIdentifier(fn.parent.name)) fname = fn.parent.name.text
        else if (fn.parent && ts.isPropertyAssignment(fn.parent)) fname = propName(fn.parent)
      }
      if (fname && HELPER_FN.test(fname)) replaceExpr(n.expression, `return in ${fname}()`)
    }
    if (ts.isCallExpression(n)) for (const i of sinkIndexes(ts, n, ctx)) replaceExpr(n.arguments[i], `${calleeName(n.expression)}() argument ${i}`)
    // 2. direct messages reads
    if ((ts.isPropertyAccessExpression(n) || ts.isElementAccessExpression(n)) && isMsgObj(n.expression) && !(n.parent && ts.isCallExpression(n.parent) && n.parent.expression === n) && !inside(n, p => ts.isFunctionLike(p) && p.parameters.length && p.parameters[0].name.getText(sf) === (ts.isElementAccessExpression(n) && n.argumentExpression.getText(sf)))) {
      use.add('__m')
      expressionEdit(n, '__m' + n.getText(sf).slice(n.expression.getText(sf).length))
      report.push({ line: lineOf(n), why: 'messages read now follows the app language', text: ts.isPropertyAccessExpression(n) ? n.name.text : n.argumentExpression.getText(sf) })
    }
    // 3. translators
    if ((ts.isArrowFunction(n) || ts.isFunctionExpression(n) || ts.isFunctionDeclaration(n) || ts.isMethodDeclaration(n)) && msgNames.size) patchTranslator(n)
    ts.forEachChild(n, visit)
  }
  visit(sf)
  for (const e of uiExpressions(ts, sf, ctx)) replaceExpr(e, 'local UI flow')
  if (!edits.length && !ctx.entry) return { file, changed: false, report }

  // 4. intl capture: default-exported component (class render / first parameter of a function)
  const captures = []
  let defName = null
  for (const st of sf.statements) {
    if (ts.isExportAssignment(st)) {
      let e = st.expression
      while (ts.isCallExpression(e) && e.arguments.length) e = e.arguments[e.arguments.length - 1] // connect(...)(Widget), memo(Widget)
      if (ts.isIdentifier(e)) defName = e.text
    }
  }
  const isDefault = d => d.modifiers && d.modifiers.some(m => m.kind === ts.SyntaxKind.DefaultKeyword)
  const cands = []
  for (const st of sf.statements) {
    if ((ts.isClassDeclaration(st) || ts.isFunctionDeclaration(st)) && (isDefault(st) || (st.name && st.name.text === defName))) cands.push(st)
    if (ts.isVariableStatement(st)) for (const d of st.declarationList.declarations) if (ts.isIdentifier(d.name) && d.name.text === defName && d.initializer) cands.push(d.initializer)
  }
  // a wrapper like `const Guarded = (props) => <Boundary><Widget {...props} /></Boundary>`: also capture in Widget
  for (const st of sf.statements) if (ts.isVariableStatement(st)) for (const d of st.declarationList.declarations) if (ts.isIdentifier(d.name) && /^(Widget|Setting)$/.test(d.name.text) && d.initializer && !cands.includes(d.initializer)) cands.push(d.initializer)
  for (const st of sf.statements) if (ts.isClassDeclaration(st) && st.name && /^(Widget|Setting)$/.test(st.name.text) && !cands.includes(st)) cands.push(st)
  for (const c of cands) {
    if (ts.isClassDeclaration(c)) {
      const r = c.members.find(m => ts.isMethodDeclaration(m) && m.name.getText(sf) === 'render' && m.body)
      if (r) captures.push({ at: r.body.getStart(sf) + 1, text: '\n    __setIntl((this.props as any).intl)' })
      continue
    }
    const fn = (ts.isArrowFunction(c) || ts.isFunctionExpression(c) || ts.isFunctionDeclaration(c)) ? c : null
    if (fn && fn.body && ts.isBlock(fn.body) && fn.parameters.length && ts.isIdentifier(fn.parameters[0].name)) {
      captures.push({ at: fn.body.getStart(sf) + 1, text: `\n  __setIntl((${fn.parameters[0].name.text} as any).intl)` })
    }
  }
  if ((ctx.entry || ctx.isEntry) && !captures.length) report.push({ line: 1, why: 'entry component not found: add __setIntl(props.intl) to its render by hand', text: '' })
  if (captures.length) use.add('__setIntl')
  for (const c of captures) if (!/^\s*__setIntl\s*\(/.test(src.slice(c.at))) edits.push({ start: c.at, end: c.at, text: c.text })
  if (!edits.length) return { file, changed: false, report }

  // imports
  const names = [...use].filter(n => !(n === '__t' && localT))
  let out = src
  // drop an edit nested inside another (the outer one already covers it)
  edits.sort((a, b) => a.start - b.start || b.end - a.end)
  const kept = []
  for (const e of edits) { const last = kept[kept.length - 1]; if (last && e.start < last.end && !(e.start === e.end)) continue; kept.push(e) }
  kept.sort((a, b) => b.start - a.start || b.end - a.end)
  for (const e of kept) out = out.slice(0, e.start) + e.text + out.slice(e.end)
  const existing = out.match(new RegExp(`import \\{([^}]*)\\} from '${relImport(file, ctx.helperNoExt).replace(/[.*+?^${}()|[\]\\/]/g, '\\$&')}'`))
  if (existing) {
    const have = new Set(existing[1].split(',').map(s => s.trim()).filter(Boolean))
    names.forEach(n => have.add(n))
    out = out.replace(existing[0], `import { ${[...have].sort().join(', ')} } from '${relImport(file, ctx.helperNoExt)}'`)
  } else if (names.length) {
    const imps = sf.statements.filter(s => ts.isImportDeclaration(s))
    const line = `import { ${names.sort().join(', ')} } from '${relImport(file, ctx.helperNoExt)}'\n`
    if (imps.length) {
      // position in the edited text: imports precede every edit, so the original offset is still valid
      const at = imps[imps.length - 1].end
      out = out.slice(0, at) + '\n' + line.replace(/\n$/, '') + out.slice(at)
    } else out = line + out
  }
  return { file, changed: out !== src, output: eol === '\r\n' ? out.replace(/\n/g, '\r\n') : out, report }
}

/** Creates a file only if it does not exist yet, in one step (no check-then-write race). */
function writeNew (file, text) {
  try { fs.writeFileSync(file, text, { encoding: 'utf8', flag: 'wx' }); return true } catch (e) { if (e.code === 'EEXIST') return false; throw e }
}

/** Wire one widget. opts: { client, apply } */
function wireWidget (widgetDir, opts = {}) {
  const ts = loadTypeScript(opts.client)
  if (!ts) throw new Error('TypeScript not found. Pass --client <EB client folder> (it ships typescript).')
  const srcDir = path.join(widgetDir, 'src')
  const parts = {}
  for (const part of ['runtime', 'setting']) {
    const def = path.join(srcDir, part, 'translations', 'default.ts')
    if (!fs.existsSync(path.join(srcDir, part))) continue
    parts[part] = { def, existed: fs.existsSync(def), keyer: makeKeyer(fs.existsSync(def) ? loadDefaultTs(def) : {}, ''), helper: path.join(srcDir, part, HELPER + '.ts'), used: false }
  }
  if (!parts.runtime || !parts.runtime.existed) return { widget: path.basename(widgetDir), skipped: 'no src/runtime/translations/default.ts', results: [] }
  const results = []
  for (const file of walk(srcDir)) {
    const rel = path.relative(srcDir, file).replace(/\\/g, '/')
    const part = rel.startsWith('setting/') && parts.setting ? 'setting' : 'runtime'
    const p = parts[part]
    const entry = /^runtime\/widget\.(tsx|ts|jsx|js)$/.test(rel) || /^setting\/setting\.(tsx|ts|jsx|js)$/.test(rel)
    const r = wireFile(ts, file, { keyFor: s => p.keyer.keyFor(s).key, helperNoExt: p.helper.replace(/\.ts$/, ''), entry: false, isEntry: entry, sinks: opts.sinks, sinkArgs: opts.sinkArgs, localizeFormats: opts.localizeFormats })
    r.rel = rel; r.part = part; r.entry = entry
    results.push(r)
    if (r.changed) p.used = true
  }
  // entry components must hand over intl whenever another module of the part uses the helper
  for (const r of results) {
    if (!r.entry || r.changed || !parts[r.part].used) continue
    const p = parts[r.part]
    const again = wireFile(ts, r.file, { keyFor: s => p.keyer.keyFor(s).key, helperNoExt: p.helper.replace(/\.ts$/, ''), entry: true, sinks: opts.sinks, sinkArgs: opts.sinkArgs })
    Object.assign(r, again)
  }
  const changedFiles = results.filter(r => r.changed)
  if (opts.apply && changedFiles.length) {
    if (opts.localizeFormats) for (const p of Object.values(parts)) {
      if (p.used && fs.existsSync(p.helper) && !/export function __locale\b/.test(fs.readFileSync(p.helper, 'utf8')) && !/\blet intl\s*:/.test(fs.readFileSync(p.helper, 'utf8'))) throw new Error(`Add __locale to the custom helper by hand: ${p.helper}`)
    }
    const stamp = new Date().toISOString().replace(/[:.]/g, '-') + '-' + require('crypto').randomBytes(4).toString('hex') + '-wire'
    const backup = path.join(widgetDir, 'i18n', 'backup', stamp)
    const created = []
    for (const r of changedFiles) { const d = path.join(backup, path.relative(widgetDir, r.file)); fs.mkdirSync(path.dirname(d), { recursive: true }); fs.copyFileSync(r.file, d) }
    for (const p of Object.values(parts)) {
      if (!p.used) continue
      if (p.existed) { const d = path.join(backup, path.relative(widgetDir, p.def)); fs.mkdirSync(path.dirname(d), { recursive: true }); fs.copyFileSync(p.def, d) }
      else { fs.mkdirSync(path.dirname(p.def), { recursive: true }); if (writeNew(p.def, 'export default {\n}\n')) created.push(path.relative(widgetDir, p.def)) }
      if (writeNew(p.helper, helperSource('./translations/default'))) created.push(path.relative(widgetDir, p.helper))
      else if (opts.localizeFormats && !/export function __locale\b/.test(fs.readFileSync(p.helper, 'utf8'))) {
        const d = path.join(backup, path.relative(widgetDir, p.helper)); fs.mkdirSync(path.dirname(d), { recursive: true }); fs.copyFileSync(p.helper, d)
        fs.appendFileSync(p.helper, '\n' + localeHelper)
      }
      appendKeys(p.def, p.keyer.added)
    }
    if (created.length) fs.writeFileSync(path.join(backup, '.created-files.json'), JSON.stringify(created))
    for (const r of changedFiles) fs.writeFileSync(r.file, r.output, 'utf8')
  }
  const added = {}
  for (const [k, p] of Object.entries(parts)) added[k] = p.keyer.added
  return { widget: path.basename(widgetDir), results, added }
}

function formatWire (r, apply) {
  if (r.skipped) return `${r.widget}: skipped (${r.skipped})`
  const changed = r.results.filter(x => x.changed)
  const keys = Object.values(r.added).reduce((n, a) => n + Object.keys(a).length, 0)
  const lines = [`${r.widget}: ${changed.length} file(s) ${apply ? 'wired' : 'to wire'}, ${keys} new key(s)`]
  for (const x of r.results) for (const p of x.report) if (/by hand/.test(p.why)) lines.push(`  ! ${x.rel}: ${p.why}`)
  return lines.join('\n')
}

module.exports = { wireWidget, wireFile, formatWire, helperSource }
